name: Build and Test Apple Watch Package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Xcode and Simulator
      uses: muukii/actions-xcode-install-simulator@1.0.0
      with:
        ios_version: 13.7
    - name: Create Simulator
      run: |
        AVAILABLE_SIMULATORS=($(xcrun simctl list devices | grep "watchOS" | awk '{print $2}'))
        xcrun simctl create "watchOS Simulator" ${AVAILABLE_SIMULATORS[0]}
    - name: Build package for watchOS
      run: |
        xcrun simctl list devices
        DEVICE_NAME=$(xcrun simctl list devices | grep "watchOS Simulator" | awk '{print $5}')
        swift build --product WatchShaker --destination="$DEVICE_NAME" -c release
    - name: Test package for watchOS
      run: |
        DEVICE_NAME=$(xcrun simctl list devices | grep "watchOS Simulator" | awk '{print $5}')
        swift test --product WatchShakerTests --destination="$DEVICE_NAME" -c release
