# This workflow will build a Swift package for watchOS

name: Swift Package - watchOS build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: swift package update
    - name: Build watchOS target
      run: swift build -c release -v --destination watchos
