name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: swift package resolve
    - name: Build for watchOS
      run: swift build -c release -Xswiftc "-target" -Xswiftc "watchos" -v
    - name: Test for watchOS
      run: swift test -c release -Xswiftc "-target" -Xswiftc "watchos" -v
