# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: 14.0
    - name: Build package
      run: swift build -c release --destination watchos
    - name: Run tests
      run: swift test -c release --destination watchos

