name: Build Apple Watch Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: swift package resolve
    - name: Build package
      run: swift build -c release --destination watchos -Xswiftc -target -Xswiftc arm64-apple-watchos7.0 -v
    - name: Test package
      run: swift test -c release --destination watchos -Xswiftc -target -Xswiftc arm64-apple-watchos7.0 -v
